### ISSUE TITLE
Keycloak 502 Bad Gateway on minio login

### ISSUE THREAD

**Issue by Synpheros** [e-ucm/simva-infra#14]
Pasos sencillos para reproducir:

1. Acceder a https://minio.simva.e-ucm.es/minio/login
2. Click en "Log in with OpenID"
3. Login normal
4. Click en Atras del navegador.

https://sso.simva.e-ucm.es/auth/realms/simva/protocol/openid-connect/auth?response_type=id_token&scope=openid+policy_role_attribute&client_id=minio&redirect_uri=https%3A%2F%2Fminio.simva.e-ucm.es%2Fminio%2Flogin%2Fopenid&nonce=pPlC9saXMEptZdNd

![image](https://user-images.githubusercontent.com/5239973/95842925-6bf52880-0d47-11eb-8e14-2d84cfc96f47.png)

**Comment by imartinezortiz** [comment]
There was an issue with the nginx LB we had. Changed the configuration because keycloak seems to generated large headers that nginx couldn't process with the previous configuration.
I'll also add the very same configuration to the nginx LB we can configure in development so we can easily reproduce this type of problems.
